package com.loyalty.pkg.helpers;

public class HTML {

	public static String htmlEmailTemplete(String token, String code) {
        
		// Verify Account URL:
		String url= "http://127.0.0.1:8081/verify?token=" + token + "&code=" +code;
		
		String emailTamplete = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>verify</title>\r\n"
				+ "    <style>\r\n"
				+ "        *{\r\n"
				+ "    box-sizing: border-box;\r\n"
				+ "    font-family: Comfortaa;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* Main Body Styling */\r\n"
				+ "body{\r\n"
				+ "    height: 100vh;\r\n"
				+ "    background-color: rgb(212, 222, 230);\r\n"
				+ "    display: flex;\r\n"
				+ "    align-items: center;\r\n"
				+ "    justify-content: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Wrapper -->*/\r\n"
				+ ".wrapper{\r\n"
				+ "    width: 550px;\r\n"
				+ "    height: auto;\r\n"
				+ "    padding: 15px;\r\n"
				+ "    background-color: white;\r\n"
				+ "    border-radius: 7px;\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Email MSG Header --> */\r\n"
				+ ".email-msg-header{\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Company Name --> */\r\n"
				+ ".company-name{\r\n"
				+ "    width: 100%;\r\n"
				+ "    font-size: 35px;\r\n"
				+ "    color: gray;\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Welcome Text --> */\r\n"
				+ ".welcome-text{\r\n"
				+ "    text-align: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Verify Account Button --> */\r\n"
				+ ".verify-account-btn{\r\n"
				+ "    padding: 15px;\r\n"
				+ "    background-color: rgb(0, 109, 252);\r\n"
				+ "    text-decoration: none;\r\n"
				+ "    color: white;\r\n"
				+ "    border-radius: 5px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* <!-- Copy Right Wrapper --> */\r\n"
				+ ".copy-right{\r\n"
				+ "    padding: 15px;\r\n"
				+ "    color: gray;\r\n"
				+ "    font-size: 14px;\r\n"
				+ "    margin: 20px 0px;\r\n"
				+ "    display: flex;\r\n"
				+ "    align-items: center;\r\n"
				+ "    justify-content: center;\r\n"
				+ "}\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ " <!-- Wrapper -->\r\n"
				+ "    <div class='wrapper'>\r\n"
				+ "           <!-- Email MSG Header -->\r\n"
				+ "           <h2 class='email-msg-header'>\r\n"
				+ "               Welcome and Thank You for Choosing  \r\n"
				+ "           </h2>\r\n"
				+ "           <!-- End Of Email MSG Header -->\r\n"
				+ "   \r\n"
				+ "           <!-- Company Name -->\r\n"
				+ "           <div class='company-name'>Customer Loyalty Program</div>\r\n"
				+ "           <!-- End Of Company Name -->\r\n"
				+ "           <hr>\r\n"
				+ "   \r\n"
				+ "           <!-- Welcome Text -->\r\n"
				+ "           <p class='welcome-text'>\r\n"
				+ "               Your Account has been successfully registered, please click below to verify your account \r\n"
				+ "           </p>\r\n"
				+ "           <!-- End Of Welcome Text -->\r\n"
				+ "           <br>\r\n"
				+ "           <br>\r\n"
				+ "   \r\n"
				+ "           <!-- Verify Account Button -->\r\n"
				+ "          <center><a href='"+ url +"' class='verify-account-btn' role='button'>Verify Account</a></center> \r\n"
				+ "           <!-- End Of Verify Account Button -->\r\n"
				+ "   \r\n"
				+ "           <!-- Copy Right Wrapper -->\r\n"
				+ "           <div class='copy-right'>\r\n"
				+ "               &copy; Copy Right 2023. All Rights Reserved.\r\n"
				+ "           </div>\r\n"
				+ "           <!-- End Of Copy Right Wrapper -->\r\n"
				+ "   \r\n"
				+ "       </div>\r\n"
				+ "       <!-- End Of Wrapper -->\r\n"
				+ "\r\n"
				+ "    \r\n"
				+ "</body>\r\n"
				+ "</html>";
		
		return emailTamplete;

	}

}
